// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "back_substitute_alt.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic back_substitute_alt::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic back_substitute_alt::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> back_substitute_alt::ap_ST_fsm_state1 = "1";
const sc_lv<7> back_substitute_alt::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<7> back_substitute_alt::ap_ST_fsm_state8 = "100";
const sc_lv<7> back_substitute_alt::ap_ST_fsm_state9 = "1000";
const sc_lv<7> back_substitute_alt::ap_ST_fsm_state10 = "10000";
const sc_lv<7> back_substitute_alt::ap_ST_fsm_pp1_stage0 = "100000";
const sc_lv<7> back_substitute_alt::ap_ST_fsm_state13 = "1000000";
const bool back_substitute_alt::ap_const_boolean_1 = true;
const sc_lv<32> back_substitute_alt::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> back_substitute_alt::ap_const_lv32_1 = "1";
const bool back_substitute_alt::ap_const_boolean_0 = false;
const sc_lv<1> back_substitute_alt::ap_const_lv1_0 = "0";
const sc_lv<32> back_substitute_alt::ap_const_lv32_3 = "11";
const sc_lv<32> back_substitute_alt::ap_const_lv32_4 = "100";
const sc_lv<32> back_substitute_alt::ap_const_lv32_5 = "101";
const sc_lv<1> back_substitute_alt::ap_const_lv1_1 = "1";
const sc_lv<3> back_substitute_alt::ap_const_lv3_0 = "000";
const sc_lv<32> back_substitute_alt::ap_const_lv32_2 = "10";
const sc_lv<32> back_substitute_alt::ap_const_lv32_6 = "110";
const sc_lv<2> back_substitute_alt::ap_const_lv2_0 = "00";
const sc_lv<2> back_substitute_alt::ap_const_lv2_1 = "1";
const sc_lv<2> back_substitute_alt::ap_const_lv2_2 = "10";
const sc_lv<2> back_substitute_alt::ap_const_lv2_3 = "11";
const sc_lv<32> back_substitute_alt::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<3> back_substitute_alt::ap_const_lv3_4 = "100";
const sc_lv<3> back_substitute_alt::ap_const_lv3_1 = "1";
const sc_lv<32> back_substitute_alt::ap_const_lv32_80000000 = "10000000000000000000000000000000";

back_substitute_alt::back_substitute_alt(sc_module_name name) : sc_module(name), mVcdFile(0) {
    row_sum_U = new back_substitute_ahbi("row_sum_U");
    row_sum_U->clk(ap_clk);
    row_sum_U->reset(ap_rst);
    row_sum_U->address0(row_sum_address0);
    row_sum_U->ce0(row_sum_ce0);
    row_sum_U->q0(row_sum_q0);
    row_sum_U->address1(row_sum_addr_1_reg_789);
    row_sum_U->ce1(row_sum_ce1);
    row_sum_U->we1(row_sum_we1);
    row_sum_U->d1(row_sum_d1);
    cholesky_inverse_ibs_U15 = new cholesky_inverse_ibs<1,1,32,32,32>("cholesky_inverse_ibs_U15");
    cholesky_inverse_ibs_U15->din0(row_sum_q0);
    cholesky_inverse_ibs_U15->din1(grp_fu_211_p2);
    cholesky_inverse_ibs_U15->dout(subst_sum_fu_206_p2);
    cholesky_inverse_dEe_U16 = new cholesky_inverse_dEe<1,1,32,32,32>("cholesky_inverse_dEe_U16");
    cholesky_inverse_dEe_U16->din0(grp_fu_211_p0);
    cholesky_inverse_dEe_U16->din1(grp_fu_211_p1);
    cholesky_inverse_dEe_U16->dout(grp_fu_211_p2);
    cholesky_inverse_jbC_U17 = new cholesky_inverse_jbC<1,5,32,32,32>("cholesky_inverse_jbC_U17");
    cholesky_inverse_jbC_U17->clk(ap_clk);
    cholesky_inverse_jbC_U17->reset(ap_rst);
    cholesky_inverse_jbC_U17->din0(ap_var_for_const0);
    cholesky_inverse_jbC_U17->din1(A_q0);
    cholesky_inverse_jbC_U17->ce(ap_var_for_const1);
    cholesky_inverse_jbC_U17->dout(grp_fu_217_p2);
    cholesky_inverse_kbM_U18 = new cholesky_inverse_kbM<1,1,32,32,32,32,2,32>("cholesky_inverse_kbM_U18");
    cholesky_inverse_kbM_U18->din0(diag_3_fu_56);
    cholesky_inverse_kbM_U18->din1(diag_3_1_fu_60);
    cholesky_inverse_kbM_U18->din2(diag_3_2_fu_64);
    cholesky_inverse_kbM_U18->din3(diag_3_3_fu_68);
    cholesky_inverse_kbM_U18->din4(select_column_multip_fu_336_p5);
    cholesky_inverse_kbM_U18->dout(select_column_multip_fu_336_p6);
    cholesky_inverse_kbM_U19 = new cholesky_inverse_kbM<1,1,32,32,32,32,2,32>("cholesky_inverse_kbM_U19");
    cholesky_inverse_kbM_U19->din0(column_multiplier_0_1_fu_76);
    cholesky_inverse_kbM_U19->din1(column_multiplier_0_2_fu_80);
    cholesky_inverse_kbM_U19->din2(column_multiplier_0_5_fu_84);
    cholesky_inverse_kbM_U19->din3(column_multiplier_0_6_fu_88);
    cholesky_inverse_kbM_U19->din4(tmp_34_reg_795);
    cholesky_inverse_kbM_U19->dout(tmp_33_fu_497_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( A_addr_2_reg_771 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_40_cast_fu_263_p1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( tmp_47_cast_fu_480_p1 );

    SC_METHOD(thread_B_address1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( tmp_50_cast_fu_519_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_B_ce1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_B_d0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_B_d1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( select_column_multip_1_fu_538_p3 );

    SC_METHOD(thread_B_we0);
    sensitive << ( exitcond_fu_388_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_25_fu_400_p2 );

    SC_METHOD(thread_B_we1);
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( tmp_25_reg_785 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);

    SC_METHOD(thread_ap_block_state11_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state12_pp1_stage0_iter1);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_condition_304);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( tmp_25_reg_785 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_ap_condition_632);
    sensitive << ( exitcond_fu_388_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_25_fu_400_p2 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond3_fu_229_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state11);
    sensitive << ( exitcond_fu_388_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond2_fu_292_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond2_fu_292_p2 );

    SC_METHOD(thread_column_multiplier_0_14_fu_600_p3);
    sensitive << ( column_multiplier_0_5_fu_84 );
    sensitive << ( sel_tmp3_fu_571_p2 );
    sensitive << ( column_multiplier_0_9_fu_592_p3 );

    SC_METHOD(thread_column_multiplier_0_15_fu_608_p3);
    sensitive << ( column_multiplier_0_2_fu_80 );
    sensitive << ( select_column_multip_1_fu_538_p3 );
    sensitive << ( sel_tmp1_fu_558_p2 );

    SC_METHOD(thread_column_multiplier_0_16_fu_616_p3);
    sensitive << ( column_multiplier_0_2_fu_80 );
    sensitive << ( sel_tmp3_fu_571_p2 );
    sensitive << ( column_multiplier_0_15_fu_608_p3 );

    SC_METHOD(thread_column_multiplier_0_3_fu_624_p3);
    sensitive << ( column_multiplier_0_1_fu_76 );
    sensitive << ( select_column_multip_1_fu_538_p3 );
    sensitive << ( sel_tmp3_fu_571_p2 );

    SC_METHOD(thread_column_multiplier_0_4_fu_563_p3);
    sensitive << ( column_multiplier_0_6_fu_88 );
    sensitive << ( sel_tmp1_fu_558_p2 );
    sensitive << ( column_multiplier_0_fu_550_p3 );

    SC_METHOD(thread_column_multiplier_0_7_fu_576_p3);
    sensitive << ( column_multiplier_0_6_fu_88 );
    sensitive << ( sel_tmp3_fu_571_p2 );
    sensitive << ( column_multiplier_0_4_fu_563_p3 );

    SC_METHOD(thread_column_multiplier_0_8_fu_584_p3);
    sensitive << ( column_multiplier_0_5_fu_84 );
    sensitive << ( select_column_multip_1_fu_538_p3 );
    sensitive << ( sel_tmp_fu_545_p2 );

    SC_METHOD(thread_column_multiplier_0_9_fu_592_p3);
    sensitive << ( column_multiplier_0_5_fu_84 );
    sensitive << ( sel_tmp1_fu_558_p2 );
    sensitive << ( column_multiplier_0_8_fu_584_p3 );

    SC_METHOD(thread_column_multiplier_0_fu_550_p3);
    sensitive << ( column_multiplier_0_6_fu_88 );
    sensitive << ( select_column_multip_1_fu_538_p3 );
    sensitive << ( sel_tmp_fu_545_p2 );

    SC_METHOD(thread_exitcond1_fu_350_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_exitcond2_fu_292_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i1_reg_172 );

    SC_METHOD(thread_exitcond3_fu_229_p2);
    sensitive << ( i_reg_161 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_fu_388_p2);
    sensitive << ( k_reg_195 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_grp_fu_211_p0);
    sensitive << ( A_q0 );
    sensitive << ( select_column_multip_reg_742 );
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( tmp_27_reg_805 );
    sensitive << ( ap_condition_304 );

    SC_METHOD(thread_grp_fu_211_p1);
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( tmp_27_reg_805 );
    sensitive << ( tmp_33_fu_497_p6 );
    sensitive << ( tmp_31_fu_533_p1 );
    sensitive << ( ap_condition_304 );

    SC_METHOD(thread_grp_fu_223_p2);
    sensitive << ( k_reg_195 );
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( exitcond_fu_388_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_25_fu_400_p2 );
    sensitive << ( i1_reg_172 );

    SC_METHOD(thread_i_1_fu_235_p2);
    sensitive << ( i_reg_161 );

    SC_METHOD(thread_i_2_fu_298_p2);
    sensitive << ( i1_reg_172 );

    SC_METHOD(thread_j_1_fu_356_p2);
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_k_2_fu_394_p2);
    sensitive << ( k_reg_195 );

    SC_METHOD(thread_row_sum_address0);
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( tmp_54_cast_fu_423_p1 );
    sensitive << ( tmp_51_cast_fu_454_p1 );
    sensitive << ( ap_condition_632 );

    SC_METHOD(thread_row_sum_ce0);
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( exitcond_fu_388_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( tmp_25_fu_400_p2 );

    SC_METHOD(thread_row_sum_ce1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_row_sum_d1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( tmp_29_reg_800 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( grp_fu_211_p2 );
    sensitive << ( subst_sum_fu_206_p2 );

    SC_METHOD(thread_row_sum_we1);
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( tmp_25_reg_785 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_sel_tmp1_fu_558_p2);
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( tmp_25_reg_785 );
    sensitive << ( tmp_30_reg_820 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_sel_tmp3_fu_571_p2);
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( tmp_25_reg_785 );
    sensitive << ( tmp_30_reg_820 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_sel_tmp_fu_545_p2);
    sensitive << ( tmp_23_reg_761 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( tmp_25_reg_785 );
    sensitive << ( tmp_30_reg_820 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_select_column_multip_1_fu_538_p3);
    sensitive << ( select_column_multip_reg_742 );
    sensitive << ( tmp_27_reg_805 );
    sensitive << ( grp_fu_211_p2 );

    SC_METHOD(thread_select_column_multip_fu_336_p5);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i1_reg_172 );

    SC_METHOD(thread_tmp_20_cast_fu_316_p1);
    sensitive << ( i1_reg_172 );

    SC_METHOD(thread_tmp_22_fu_362_p2);
    sensitive << ( exitcond1_fu_350_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( i1_reg_172 );
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_tmp_23_fu_368_p2);
    sensitive << ( exitcond1_fu_350_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_22_fu_362_p2 );
    sensitive << ( i1_reg_172 );
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_tmp_24_cast_fu_374_p1);
    sensitive << ( j_reg_184 );

    SC_METHOD(thread_tmp_25_fu_400_p2);
    sensitive << ( k_reg_195 );
    sensitive << ( exitcond_fu_388_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( i1_reg_172 );

    SC_METHOD(thread_tmp_30_fu_459_p1);
    sensitive << ( k_reg_195 );

    SC_METHOD(thread_tmp_31_fu_533_p1);
    sensitive << ( tmp_32_neg_fu_527_p2 );

    SC_METHOD(thread_tmp_32_neg_fu_527_p2);
    sensitive << ( tmp_32_to_int_fu_523_p1 );

    SC_METHOD(thread_tmp_32_to_int_fu_523_p1);
    sensitive << ( row_sum_q0 );

    SC_METHOD(thread_tmp_34_fu_428_p1);
    sensitive << ( k_reg_195 );

    SC_METHOD(thread_tmp_36_fu_245_p3);
    sensitive << ( i_reg_161 );

    SC_METHOD(thread_tmp_37_fu_257_p2);
    sensitive << ( tmp_39_cast_fu_253_p1 );
    sensitive << ( tmp_cast_fu_241_p1 );

    SC_METHOD(thread_tmp_38_fu_320_p3);
    sensitive << ( i1_reg_172 );

    SC_METHOD(thread_tmp_39_cast_fu_253_p1);
    sensitive << ( tmp_36_fu_245_p3 );

    SC_METHOD(thread_tmp_39_fu_378_p2);
    sensitive << ( tmp_43_cast_reg_737 );
    sensitive << ( tmp_24_cast_fu_374_p1 );

    SC_METHOD(thread_tmp_40_cast_fu_263_p1);
    sensitive << ( tmp_37_fu_257_p2 );

    SC_METHOD(thread_tmp_40_fu_463_p3);
    sensitive << ( k_reg_195 );

    SC_METHOD(thread_tmp_41_fu_475_p2);
    sensitive << ( tmp_20_cast_reg_731 );
    sensitive << ( tmp_46_cast_fu_471_p1 );

    SC_METHOD(thread_tmp_42_fu_432_p3);
    sensitive << ( k_reg_195 );

    SC_METHOD(thread_tmp_43_cast_fu_328_p1);
    sensitive << ( tmp_38_fu_320_p3 );

    SC_METHOD(thread_tmp_43_fu_444_p2);
    sensitive << ( tmp_20_cast_reg_731 );
    sensitive << ( tmp_49_cast_fu_440_p1 );

    SC_METHOD(thread_tmp_44_cast_fu_383_p1);
    sensitive << ( tmp_39_fu_378_p2 );

    SC_METHOD(thread_tmp_44_fu_449_p2);
    sensitive << ( tmp_24_cast_reg_765 );
    sensitive << ( tmp_49_cast_fu_440_p1 );

    SC_METHOD(thread_tmp_45_fu_406_p3);
    sensitive << ( k_reg_195 );

    SC_METHOD(thread_tmp_46_cast_fu_471_p1);
    sensitive << ( tmp_40_fu_463_p3 );

    SC_METHOD(thread_tmp_46_fu_418_p2);
    sensitive << ( tmp_24_cast_reg_765 );
    sensitive << ( tmp_53_cast_fu_414_p1 );

    SC_METHOD(thread_tmp_47_cast_fu_480_p1);
    sensitive << ( tmp_41_fu_475_p2 );

    SC_METHOD(thread_tmp_49_cast_fu_440_p1);
    sensitive << ( tmp_42_fu_432_p3 );

    SC_METHOD(thread_tmp_50_cast_fu_519_p1);
    sensitive << ( tmp_43_reg_810 );

    SC_METHOD(thread_tmp_51_cast_fu_454_p1);
    sensitive << ( tmp_44_fu_449_p2 );

    SC_METHOD(thread_tmp_53_cast_fu_414_p1);
    sensitive << ( tmp_45_fu_406_p3 );

    SC_METHOD(thread_tmp_54_cast_fu_423_p1);
    sensitive << ( tmp_46_fu_418_p2 );

    SC_METHOD(thread_tmp_cast_fu_241_p1);
    sensitive << ( i_reg_161 );

    SC_METHOD(thread_tmp_fu_268_p1);
    sensitive << ( i_reg_161 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond3_fu_229_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond2_fu_292_p2 );
    sensitive << ( exitcond1_fu_350_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_22_fu_362_p2 );
    sensitive << ( exitcond_fu_388_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp1_stage0_subdone );

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "back_substitute_alt_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_we0, "(port)B_we0");
    sc_trace(mVcdFile, B_d0, "(port)B_d0");
    sc_trace(mVcdFile, B_address1, "(port)B_address1");
    sc_trace(mVcdFile, B_ce1, "(port)B_ce1");
    sc_trace(mVcdFile, B_we1, "(port)B_we1");
    sc_trace(mVcdFile, B_d1, "(port)B_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_reg_161, "i_reg_161");
    sc_trace(mVcdFile, k_reg_195, "k_reg_195");
    sc_trace(mVcdFile, exitcond3_fu_229_p2, "exitcond3_fu_229_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_1_fu_235_p2, "i_1_fu_235_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_fu_268_p1, "tmp_fu_268_p1");
    sc_trace(mVcdFile, tmp_reg_690, "tmp_reg_690");
    sc_trace(mVcdFile, tmp_reg_690_pp0_iter1_reg, "tmp_reg_690_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_reg_690_pp0_iter2_reg, "tmp_reg_690_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_reg_690_pp0_iter3_reg, "tmp_reg_690_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_reg_690_pp0_iter4_reg, "tmp_reg_690_pp0_iter4_reg");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, i_2_fu_298_p2, "i_2_fu_298_p2");
    sc_trace(mVcdFile, i_2_reg_726, "i_2_reg_726");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_20_cast_fu_316_p1, "tmp_20_cast_fu_316_p1");
    sc_trace(mVcdFile, tmp_20_cast_reg_731, "tmp_20_cast_reg_731");
    sc_trace(mVcdFile, exitcond2_fu_292_p2, "exitcond2_fu_292_p2");
    sc_trace(mVcdFile, tmp_43_cast_fu_328_p1, "tmp_43_cast_fu_328_p1");
    sc_trace(mVcdFile, tmp_43_cast_reg_737, "tmp_43_cast_reg_737");
    sc_trace(mVcdFile, select_column_multip_fu_336_p6, "select_column_multip_fu_336_p6");
    sc_trace(mVcdFile, select_column_multip_reg_742, "select_column_multip_reg_742");
    sc_trace(mVcdFile, exitcond1_fu_350_p2, "exitcond1_fu_350_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, j_1_fu_356_p2, "j_1_fu_356_p2");
    sc_trace(mVcdFile, j_1_reg_752, "j_1_reg_752");
    sc_trace(mVcdFile, tmp_22_fu_362_p2, "tmp_22_fu_362_p2");
    sc_trace(mVcdFile, tmp_23_fu_368_p2, "tmp_23_fu_368_p2");
    sc_trace(mVcdFile, tmp_23_reg_761, "tmp_23_reg_761");
    sc_trace(mVcdFile, tmp_24_cast_fu_374_p1, "tmp_24_cast_fu_374_p1");
    sc_trace(mVcdFile, tmp_24_cast_reg_765, "tmp_24_cast_reg_765");
    sc_trace(mVcdFile, A_addr_2_reg_771, "A_addr_2_reg_771");
    sc_trace(mVcdFile, exitcond_fu_388_p2, "exitcond_fu_388_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_block_state11_pp1_stage0_iter0, "ap_block_state11_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state12_pp1_stage0_iter1, "ap_block_state12_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, k_2_fu_394_p2, "k_2_fu_394_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, tmp_25_fu_400_p2, "tmp_25_fu_400_p2");
    sc_trace(mVcdFile, tmp_25_reg_785, "tmp_25_reg_785");
    sc_trace(mVcdFile, row_sum_addr_1_reg_789, "row_sum_addr_1_reg_789");
    sc_trace(mVcdFile, tmp_34_fu_428_p1, "tmp_34_fu_428_p1");
    sc_trace(mVcdFile, tmp_34_reg_795, "tmp_34_reg_795");
    sc_trace(mVcdFile, grp_fu_223_p2, "grp_fu_223_p2");
    sc_trace(mVcdFile, tmp_29_reg_800, "tmp_29_reg_800");
    sc_trace(mVcdFile, tmp_27_reg_805, "tmp_27_reg_805");
    sc_trace(mVcdFile, tmp_43_fu_444_p2, "tmp_43_fu_444_p2");
    sc_trace(mVcdFile, tmp_43_reg_810, "tmp_43_reg_810");
    sc_trace(mVcdFile, tmp_30_fu_459_p1, "tmp_30_fu_459_p1");
    sc_trace(mVcdFile, tmp_30_reg_820, "tmp_30_reg_820");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state11, "ap_condition_pp1_exit_iter0_state11");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, row_sum_address0, "row_sum_address0");
    sc_trace(mVcdFile, row_sum_ce0, "row_sum_ce0");
    sc_trace(mVcdFile, row_sum_q0, "row_sum_q0");
    sc_trace(mVcdFile, row_sum_ce1, "row_sum_ce1");
    sc_trace(mVcdFile, row_sum_we1, "row_sum_we1");
    sc_trace(mVcdFile, row_sum_d1, "row_sum_d1");
    sc_trace(mVcdFile, i1_reg_172, "i1_reg_172");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, j_reg_184, "j_reg_184");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, tmp_40_cast_fu_263_p1, "tmp_40_cast_fu_263_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_44_cast_fu_383_p1, "tmp_44_cast_fu_383_p1");
    sc_trace(mVcdFile, tmp_54_cast_fu_423_p1, "tmp_54_cast_fu_423_p1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, tmp_51_cast_fu_454_p1, "tmp_51_cast_fu_454_p1");
    sc_trace(mVcdFile, tmp_47_cast_fu_480_p1, "tmp_47_cast_fu_480_p1");
    sc_trace(mVcdFile, tmp_50_cast_fu_519_p1, "tmp_50_cast_fu_519_p1");
    sc_trace(mVcdFile, diag_3_fu_56, "diag_3_fu_56");
    sc_trace(mVcdFile, grp_fu_217_p2, "grp_fu_217_p2");
    sc_trace(mVcdFile, diag_3_1_fu_60, "diag_3_1_fu_60");
    sc_trace(mVcdFile, diag_3_2_fu_64, "diag_3_2_fu_64");
    sc_trace(mVcdFile, diag_3_3_fu_68, "diag_3_3_fu_68");
    sc_trace(mVcdFile, column_multiplier_0_1_fu_76, "column_multiplier_0_1_fu_76");
    sc_trace(mVcdFile, column_multiplier_0_3_fu_624_p3, "column_multiplier_0_3_fu_624_p3");
    sc_trace(mVcdFile, column_multiplier_0_2_fu_80, "column_multiplier_0_2_fu_80");
    sc_trace(mVcdFile, column_multiplier_0_16_fu_616_p3, "column_multiplier_0_16_fu_616_p3");
    sc_trace(mVcdFile, column_multiplier_0_5_fu_84, "column_multiplier_0_5_fu_84");
    sc_trace(mVcdFile, column_multiplier_0_14_fu_600_p3, "column_multiplier_0_14_fu_600_p3");
    sc_trace(mVcdFile, column_multiplier_0_6_fu_88, "column_multiplier_0_6_fu_88");
    sc_trace(mVcdFile, column_multiplier_0_7_fu_576_p3, "column_multiplier_0_7_fu_576_p3");
    sc_trace(mVcdFile, select_column_multip_1_fu_538_p3, "select_column_multip_1_fu_538_p3");
    sc_trace(mVcdFile, grp_fu_211_p2, "grp_fu_211_p2");
    sc_trace(mVcdFile, grp_fu_211_p0, "grp_fu_211_p0");
    sc_trace(mVcdFile, grp_fu_211_p1, "grp_fu_211_p1");
    sc_trace(mVcdFile, tmp_33_fu_497_p6, "tmp_33_fu_497_p6");
    sc_trace(mVcdFile, tmp_31_fu_533_p1, "tmp_31_fu_533_p1");
    sc_trace(mVcdFile, tmp_36_fu_245_p3, "tmp_36_fu_245_p3");
    sc_trace(mVcdFile, tmp_39_cast_fu_253_p1, "tmp_39_cast_fu_253_p1");
    sc_trace(mVcdFile, tmp_cast_fu_241_p1, "tmp_cast_fu_241_p1");
    sc_trace(mVcdFile, tmp_37_fu_257_p2, "tmp_37_fu_257_p2");
    sc_trace(mVcdFile, tmp_38_fu_320_p3, "tmp_38_fu_320_p3");
    sc_trace(mVcdFile, select_column_multip_fu_336_p5, "select_column_multip_fu_336_p5");
    sc_trace(mVcdFile, tmp_39_fu_378_p2, "tmp_39_fu_378_p2");
    sc_trace(mVcdFile, tmp_45_fu_406_p3, "tmp_45_fu_406_p3");
    sc_trace(mVcdFile, tmp_53_cast_fu_414_p1, "tmp_53_cast_fu_414_p1");
    sc_trace(mVcdFile, tmp_46_fu_418_p2, "tmp_46_fu_418_p2");
    sc_trace(mVcdFile, tmp_42_fu_432_p3, "tmp_42_fu_432_p3");
    sc_trace(mVcdFile, tmp_49_cast_fu_440_p1, "tmp_49_cast_fu_440_p1");
    sc_trace(mVcdFile, tmp_44_fu_449_p2, "tmp_44_fu_449_p2");
    sc_trace(mVcdFile, tmp_40_fu_463_p3, "tmp_40_fu_463_p3");
    sc_trace(mVcdFile, tmp_46_cast_fu_471_p1, "tmp_46_cast_fu_471_p1");
    sc_trace(mVcdFile, tmp_41_fu_475_p2, "tmp_41_fu_475_p2");
    sc_trace(mVcdFile, subst_sum_fu_206_p2, "subst_sum_fu_206_p2");
    sc_trace(mVcdFile, tmp_32_to_int_fu_523_p1, "tmp_32_to_int_fu_523_p1");
    sc_trace(mVcdFile, tmp_32_neg_fu_527_p2, "tmp_32_neg_fu_527_p2");
    sc_trace(mVcdFile, sel_tmp_fu_545_p2, "sel_tmp_fu_545_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_558_p2, "sel_tmp1_fu_558_p2");
    sc_trace(mVcdFile, column_multiplier_0_fu_550_p3, "column_multiplier_0_fu_550_p3");
    sc_trace(mVcdFile, sel_tmp3_fu_571_p2, "sel_tmp3_fu_571_p2");
    sc_trace(mVcdFile, column_multiplier_0_4_fu_563_p3, "column_multiplier_0_4_fu_563_p3");
    sc_trace(mVcdFile, column_multiplier_0_8_fu_584_p3, "column_multiplier_0_8_fu_584_p3");
    sc_trace(mVcdFile, column_multiplier_0_9_fu_592_p3, "column_multiplier_0_9_fu_592_p3");
    sc_trace(mVcdFile, column_multiplier_0_15_fu_608_p3, "column_multiplier_0_15_fu_608_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, ap_condition_304, "ap_condition_304");
    sc_trace(mVcdFile, ap_condition_632, "ap_condition_632");
#endif

    }
}

back_substitute_alt::~back_substitute_alt() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete row_sum_U;
    delete cholesky_inverse_ibs_U15;
    delete cholesky_inverse_dEe_U16;
    delete cholesky_inverse_jbC_U17;
    delete cholesky_inverse_kbM_U18;
    delete cholesky_inverse_kbM_U19;
}

void back_substitute_alt::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_1;
}

void back_substitute_alt::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_3F800000;
}

void back_substitute_alt::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter5 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state11.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(tmp_22_fu_362_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(exitcond1_fu_350_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state11.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state11.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read())) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if ((esl_seteq<1,1,1>(tmp_22_fu_362_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(exitcond1_fu_350_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i1_reg_172 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_350_p2.read(), ap_const_lv1_1))) {
        i1_reg_172 = i_2_reg_726.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(exitcond3_fu_229_p2.read(), ap_const_lv1_0))) {
        i_reg_161 = i_1_fu_235_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_161 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_reg_184 = j_1_reg_752.read();
    } else if ((esl_seteq<1,1,1>(exitcond2_fu_292_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        j_reg_184 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()))) {
        k_reg_195 = k_2_fu_394_p2.read();
    } else if ((esl_seteq<1,1,1>(tmp_22_fu_362_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(exitcond1_fu_350_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        k_reg_195 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(tmp_22_fu_362_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(exitcond1_fu_350_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        A_addr_2_reg_771 =  (sc_lv<4>) (tmp_44_cast_fu_383_p1.read());
        tmp_23_reg_761 = tmp_23_fu_368_p2.read();
        tmp_24_cast_reg_765 = tmp_24_cast_fu_374_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_23_reg_761.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_reg_785.read()))) {
        column_multiplier_0_1_fu_76 = column_multiplier_0_3_fu_624_p3.read();
        column_multiplier_0_2_fu_80 = column_multiplier_0_16_fu_616_p3.read();
        column_multiplier_0_5_fu_84 = column_multiplier_0_14_fu_600_p3.read();
        column_multiplier_0_6_fu_88 = column_multiplier_0_7_fu_576_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && esl_seteq<1,2,2>(tmp_reg_690_pp0_iter4_reg.read(), ap_const_lv2_1))) {
        diag_3_1_fu_60 = grp_fu_217_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && esl_seteq<1,2,2>(tmp_reg_690_pp0_iter4_reg.read(), ap_const_lv2_2))) {
        diag_3_2_fu_64 = grp_fu_217_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && esl_seteq<1,2,2>(tmp_reg_690_pp0_iter4_reg.read(), ap_const_lv2_3))) {
        diag_3_3_fu_68 = grp_fu_217_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && esl_seteq<1,2,2>(tmp_reg_690_pp0_iter4_reg.read(), ap_const_lv2_0))) {
        diag_3_fu_56 = grp_fu_217_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_2_reg_726 = i_2_fu_298_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        j_1_reg_752 = j_1_fu_356_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_fu_400_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_reg_761.read()))) {
        row_sum_addr_1_reg_789 =  (sc_lv<4>) (tmp_54_cast_fu_423_p1.read());
        tmp_34_reg_795 = tmp_34_fu_428_p1.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_fu_292_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        select_column_multip_reg_742 = select_column_multip_fu_336_p6.read();
        tmp_20_cast_reg_731 = tmp_20_cast_fu_316_p1.read();
        tmp_43_cast_reg_737 = tmp_43_cast_fu_328_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()))) {
        tmp_25_reg_785 = tmp_25_fu_400_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_fu_400_p2.read()) && esl_seteq<1,1,1>(tmp_23_reg_761.read(), ap_const_lv1_1))) {
        tmp_27_reg_805 = grp_fu_223_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_fu_400_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_reg_761.read()))) {
        tmp_29_reg_800 = grp_fu_223_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_fu_400_p2.read()) && esl_seteq<1,1,1>(tmp_23_reg_761.read(), ap_const_lv1_1))) {
        tmp_30_reg_820 = tmp_30_fu_459_p1.read();
        tmp_43_reg_810 = tmp_43_fu_444_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond3_fu_229_p2.read(), ap_const_lv1_0))) {
        tmp_reg_690 = tmp_fu_268_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_reg_690_pp0_iter1_reg = tmp_reg_690.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        tmp_reg_690_pp0_iter2_reg = tmp_reg_690_pp0_iter1_reg.read();
        tmp_reg_690_pp0_iter3_reg = tmp_reg_690_pp0_iter2_reg.read();
        tmp_reg_690_pp0_iter4_reg = tmp_reg_690_pp0_iter3_reg.read();
    }
}

void back_substitute_alt::thread_A_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        A_address0 = A_addr_2_reg_771.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        A_address0 =  (sc_lv<4>) (tmp_40_cast_fu_263_p1.read());
    } else {
        A_address0 = "XXXX";
    }
}

void back_substitute_alt::thread_A_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1)))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_B_address0() {
    B_address0 =  (sc_lv<4>) (tmp_47_cast_fu_480_p1.read());
}

void back_substitute_alt::thread_B_address1() {
    B_address1 =  (sc_lv<4>) (tmp_50_cast_fu_519_p1.read());
}

void back_substitute_alt::thread_B_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1))) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_B_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        B_ce1 = ap_const_logic_1;
    } else {
        B_ce1 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_B_d0() {
    B_d0 = ap_const_lv32_0;
}

void back_substitute_alt::thread_B_d1() {
    B_d1 = select_column_multip_1_fu_538_p3.read();
}

void back_substitute_alt::thread_B_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()) && 
         esl_seteq<1,1,1>(tmp_25_fu_400_p2.read(), ap_const_lv1_1))) {
        B_we0 = ap_const_logic_1;
    } else {
        B_we0 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_B_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_23_reg_761.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_reg_785.read()))) {
        B_we1 = ap_const_logic_1;
    } else {
        B_we1 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void back_substitute_alt::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[5];
}

void back_substitute_alt::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void back_substitute_alt::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[4];
}

void back_substitute_alt::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[6];
}

void back_substitute_alt::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[2];
}

void back_substitute_alt::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[3];
}

void back_substitute_alt::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_state11_pp1_stage0_iter0() {
    ap_block_state11_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_state12_pp1_stage0_iter1() {
    ap_block_state12_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void back_substitute_alt::thread_ap_condition_304() {
    ap_condition_304 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_reg_785.read()));
}

void back_substitute_alt::thread_ap_condition_632() {
    ap_condition_632 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_fu_400_p2.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0));
}

void back_substitute_alt::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond3_fu_229_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_ap_condition_pp1_exit_iter0_state11() {
    if (esl_seteq<1,1,1>(exitcond_fu_388_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state11 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state11 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_292_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void back_substitute_alt::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void back_substitute_alt::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_292_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_column_multiplier_0_14_fu_600_p3() {
    column_multiplier_0_14_fu_600_p3 = (!sel_tmp3_fu_571_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp3_fu_571_p2.read()[0].to_bool())? column_multiplier_0_5_fu_84.read(): column_multiplier_0_9_fu_592_p3.read());
}

void back_substitute_alt::thread_column_multiplier_0_15_fu_608_p3() {
    column_multiplier_0_15_fu_608_p3 = (!sel_tmp1_fu_558_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp1_fu_558_p2.read()[0].to_bool())? select_column_multip_1_fu_538_p3.read(): column_multiplier_0_2_fu_80.read());
}

void back_substitute_alt::thread_column_multiplier_0_16_fu_616_p3() {
    column_multiplier_0_16_fu_616_p3 = (!sel_tmp3_fu_571_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp3_fu_571_p2.read()[0].to_bool())? column_multiplier_0_2_fu_80.read(): column_multiplier_0_15_fu_608_p3.read());
}

void back_substitute_alt::thread_column_multiplier_0_3_fu_624_p3() {
    column_multiplier_0_3_fu_624_p3 = (!sel_tmp3_fu_571_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp3_fu_571_p2.read()[0].to_bool())? select_column_multip_1_fu_538_p3.read(): column_multiplier_0_1_fu_76.read());
}

void back_substitute_alt::thread_column_multiplier_0_4_fu_563_p3() {
    column_multiplier_0_4_fu_563_p3 = (!sel_tmp1_fu_558_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp1_fu_558_p2.read()[0].to_bool())? column_multiplier_0_6_fu_88.read(): column_multiplier_0_fu_550_p3.read());
}

void back_substitute_alt::thread_column_multiplier_0_7_fu_576_p3() {
    column_multiplier_0_7_fu_576_p3 = (!sel_tmp3_fu_571_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp3_fu_571_p2.read()[0].to_bool())? column_multiplier_0_6_fu_88.read(): column_multiplier_0_4_fu_563_p3.read());
}

void back_substitute_alt::thread_column_multiplier_0_8_fu_584_p3() {
    column_multiplier_0_8_fu_584_p3 = (!sel_tmp_fu_545_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_fu_545_p2.read()[0].to_bool())? select_column_multip_1_fu_538_p3.read(): column_multiplier_0_5_fu_84.read());
}

void back_substitute_alt::thread_column_multiplier_0_9_fu_592_p3() {
    column_multiplier_0_9_fu_592_p3 = (!sel_tmp1_fu_558_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp1_fu_558_p2.read()[0].to_bool())? column_multiplier_0_5_fu_84.read(): column_multiplier_0_8_fu_584_p3.read());
}

void back_substitute_alt::thread_column_multiplier_0_fu_550_p3() {
    column_multiplier_0_fu_550_p3 = (!sel_tmp_fu_545_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_fu_545_p2.read()[0].to_bool())? column_multiplier_0_6_fu_88.read(): select_column_multip_1_fu_538_p3.read());
}

void back_substitute_alt::thread_exitcond1_fu_350_p2() {
    exitcond1_fu_350_p2 = (!j_reg_184.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_184.read() == ap_const_lv3_4);
}

void back_substitute_alt::thread_exitcond2_fu_292_p2() {
    exitcond2_fu_292_p2 = (!i1_reg_172.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_172.read() == ap_const_lv3_4);
}

void back_substitute_alt::thread_exitcond3_fu_229_p2() {
    exitcond3_fu_229_p2 = (!i_reg_161.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_161.read() == ap_const_lv3_4);
}

void back_substitute_alt::thread_exitcond_fu_388_p2() {
    exitcond_fu_388_p2 = (!k_reg_195.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_195.read() == ap_const_lv3_4);
}

void back_substitute_alt::thread_grp_fu_211_p0() {
    if (esl_seteq<1,1,1>(ap_condition_304.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(tmp_23_reg_761.read(), ap_const_lv1_1) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_805.read()))) {
            grp_fu_211_p0 = select_column_multip_reg_742.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_reg_761.read())) {
            grp_fu_211_p0 = A_q0.read();
        } else {
            grp_fu_211_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_fu_211_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void back_substitute_alt::thread_grp_fu_211_p1() {
    if (esl_seteq<1,1,1>(ap_condition_304.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(tmp_23_reg_761.read(), ap_const_lv1_1) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, tmp_27_reg_805.read()))) {
            grp_fu_211_p1 = tmp_31_fu_533_p1.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_reg_761.read())) {
            grp_fu_211_p1 = tmp_33_fu_497_p6.read();
        } else {
            grp_fu_211_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_fu_211_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void back_substitute_alt::thread_grp_fu_223_p2() {
    grp_fu_223_p2 = (!k_reg_195.read().is_01() || !i1_reg_172.read().is_01())? sc_lv<1>(): sc_lv<1>(k_reg_195.read() == i1_reg_172.read());
}

void back_substitute_alt::thread_i_1_fu_235_p2() {
    i_1_fu_235_p2 = (!i_reg_161.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_reg_161.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void back_substitute_alt::thread_i_2_fu_298_p2() {
    i_2_fu_298_p2 = (!i1_reg_172.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i1_reg_172.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void back_substitute_alt::thread_j_1_fu_356_p2() {
    j_1_fu_356_p2 = (!j_reg_184.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_reg_184.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void back_substitute_alt::thread_k_2_fu_394_p2() {
    k_2_fu_394_p2 = (!k_reg_195.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k_reg_195.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void back_substitute_alt::thread_row_sum_address0() {
    if (esl_seteq<1,1,1>(ap_condition_632.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(tmp_23_reg_761.read(), ap_const_lv1_1)) {
            row_sum_address0 =  (sc_lv<4>) (tmp_51_cast_fu_454_p1.read());
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_reg_761.read())) {
            row_sum_address0 =  (sc_lv<4>) (tmp_54_cast_fu_423_p1.read());
        } else {
            row_sum_address0 = "XXXX";
        }
    } else {
        row_sum_address0 = "XXXX";
    }
}

void back_substitute_alt::thread_row_sum_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_fu_400_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_reg_761.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_388_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_fu_400_p2.read()) && 
          esl_seteq<1,1,1>(tmp_23_reg_761.read(), ap_const_lv1_1)))) {
        row_sum_ce0 = ap_const_logic_1;
    } else {
        row_sum_ce0 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_row_sum_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        row_sum_ce1 = ap_const_logic_1;
    } else {
        row_sum_ce1 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_row_sum_d1() {
    row_sum_d1 = (!tmp_29_reg_800.read()[0].is_01())? sc_lv<32>(): ((tmp_29_reg_800.read()[0].to_bool())? grp_fu_211_p2.read(): subst_sum_fu_206_p2.read());
}

void back_substitute_alt::thread_row_sum_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_23_reg_761.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_25_reg_785.read()))) {
        row_sum_we1 = ap_const_logic_1;
    } else {
        row_sum_we1 = ap_const_logic_0;
    }
}

void back_substitute_alt::thread_sel_tmp1_fu_558_p2() {
    sel_tmp1_fu_558_p2 = (!tmp_30_reg_820.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_820.read() == ap_const_lv2_1);
}

void back_substitute_alt::thread_sel_tmp3_fu_571_p2() {
    sel_tmp3_fu_571_p2 = (!tmp_30_reg_820.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_820.read() == ap_const_lv2_0);
}

void back_substitute_alt::thread_sel_tmp_fu_545_p2() {
    sel_tmp_fu_545_p2 = (!tmp_30_reg_820.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_820.read() == ap_const_lv2_2);
}

void back_substitute_alt::thread_select_column_multip_1_fu_538_p3() {
    select_column_multip_1_fu_538_p3 = (!tmp_27_reg_805.read()[0].is_01())? sc_lv<32>(): ((tmp_27_reg_805.read()[0].to_bool())? select_column_multip_reg_742.read(): grp_fu_211_p2.read());
}

void back_substitute_alt::thread_select_column_multip_fu_336_p5() {
    select_column_multip_fu_336_p5 = i1_reg_172.read().range(2-1, 0);
}

void back_substitute_alt::thread_tmp_20_cast_fu_316_p1() {
    tmp_20_cast_fu_316_p1 = esl_zext<6,3>(i1_reg_172.read());
}

void back_substitute_alt::thread_tmp_22_fu_362_p2() {
    tmp_22_fu_362_p2 = (!j_reg_184.read().is_01() || !i1_reg_172.read().is_01())? sc_lv<1>(): (sc_biguint<3>(j_reg_184.read()) < sc_biguint<3>(i1_reg_172.read()));
}

void back_substitute_alt::thread_tmp_23_fu_368_p2() {
    tmp_23_fu_368_p2 = (!i1_reg_172.read().is_01() || !j_reg_184.read().is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_172.read() == j_reg_184.read());
}

void back_substitute_alt::thread_tmp_24_cast_fu_374_p1() {
    tmp_24_cast_fu_374_p1 = esl_zext<6,3>(j_reg_184.read());
}

void back_substitute_alt::thread_tmp_25_fu_400_p2() {
    tmp_25_fu_400_p2 = (!k_reg_195.read().is_01() || !i1_reg_172.read().is_01())? sc_lv<1>(): (sc_biguint<3>(k_reg_195.read()) > sc_biguint<3>(i1_reg_172.read()));
}

void back_substitute_alt::thread_tmp_30_fu_459_p1() {
    tmp_30_fu_459_p1 = k_reg_195.read().range(2-1, 0);
}

void back_substitute_alt::thread_tmp_31_fu_533_p1() {
    tmp_31_fu_533_p1 = tmp_32_neg_fu_527_p2.read();
}

void back_substitute_alt::thread_tmp_32_neg_fu_527_p2() {
    tmp_32_neg_fu_527_p2 = (tmp_32_to_int_fu_523_p1.read() ^ ap_const_lv32_80000000);
}

void back_substitute_alt::thread_tmp_32_to_int_fu_523_p1() {
    tmp_32_to_int_fu_523_p1 = row_sum_q0.read();
}

void back_substitute_alt::thread_tmp_34_fu_428_p1() {
    tmp_34_fu_428_p1 = k_reg_195.read().range(2-1, 0);
}

void back_substitute_alt::thread_tmp_36_fu_245_p3() {
    tmp_36_fu_245_p3 = esl_concat<3,2>(i_reg_161.read(), ap_const_lv2_0);
}

void back_substitute_alt::thread_tmp_37_fu_257_p2() {
    tmp_37_fu_257_p2 = (!tmp_39_cast_fu_253_p1.read().is_01() || !tmp_cast_fu_241_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_39_cast_fu_253_p1.read()) + sc_biguint<6>(tmp_cast_fu_241_p1.read()));
}

void back_substitute_alt::thread_tmp_38_fu_320_p3() {
    tmp_38_fu_320_p3 = esl_concat<3,2>(i1_reg_172.read(), ap_const_lv2_0);
}

void back_substitute_alt::thread_tmp_39_cast_fu_253_p1() {
    tmp_39_cast_fu_253_p1 = esl_zext<6,5>(tmp_36_fu_245_p3.read());
}

void back_substitute_alt::thread_tmp_39_fu_378_p2() {
    tmp_39_fu_378_p2 = (!tmp_43_cast_reg_737.read().is_01() || !tmp_24_cast_fu_374_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_43_cast_reg_737.read()) + sc_biguint<6>(tmp_24_cast_fu_374_p1.read()));
}

void back_substitute_alt::thread_tmp_40_cast_fu_263_p1() {
    tmp_40_cast_fu_263_p1 = esl_zext<64,6>(tmp_37_fu_257_p2.read());
}

void back_substitute_alt::thread_tmp_40_fu_463_p3() {
    tmp_40_fu_463_p3 = esl_concat<3,2>(k_reg_195.read(), ap_const_lv2_0);
}

void back_substitute_alt::thread_tmp_41_fu_475_p2() {
    tmp_41_fu_475_p2 = (!tmp_20_cast_reg_731.read().is_01() || !tmp_46_cast_fu_471_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_20_cast_reg_731.read()) + sc_biguint<6>(tmp_46_cast_fu_471_p1.read()));
}

void back_substitute_alt::thread_tmp_42_fu_432_p3() {
    tmp_42_fu_432_p3 = esl_concat<3,2>(k_reg_195.read(), ap_const_lv2_0);
}

void back_substitute_alt::thread_tmp_43_cast_fu_328_p1() {
    tmp_43_cast_fu_328_p1 = esl_zext<6,5>(tmp_38_fu_320_p3.read());
}

void back_substitute_alt::thread_tmp_43_fu_444_p2() {
    tmp_43_fu_444_p2 = (!tmp_49_cast_fu_440_p1.read().is_01() || !tmp_20_cast_reg_731.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_49_cast_fu_440_p1.read()) + sc_biguint<6>(tmp_20_cast_reg_731.read()));
}

void back_substitute_alt::thread_tmp_44_cast_fu_383_p1() {
    tmp_44_cast_fu_383_p1 = esl_zext<64,6>(tmp_39_fu_378_p2.read());
}

void back_substitute_alt::thread_tmp_44_fu_449_p2() {
    tmp_44_fu_449_p2 = (!tmp_49_cast_fu_440_p1.read().is_01() || !tmp_24_cast_reg_765.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_49_cast_fu_440_p1.read()) + sc_biguint<6>(tmp_24_cast_reg_765.read()));
}

void back_substitute_alt::thread_tmp_45_fu_406_p3() {
    tmp_45_fu_406_p3 = esl_concat<3,2>(k_reg_195.read(), ap_const_lv2_0);
}

void back_substitute_alt::thread_tmp_46_cast_fu_471_p1() {
    tmp_46_cast_fu_471_p1 = esl_zext<6,5>(tmp_40_fu_463_p3.read());
}

void back_substitute_alt::thread_tmp_46_fu_418_p2() {
    tmp_46_fu_418_p2 = (!tmp_53_cast_fu_414_p1.read().is_01() || !tmp_24_cast_reg_765.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_53_cast_fu_414_p1.read()) + sc_biguint<6>(tmp_24_cast_reg_765.read()));
}

void back_substitute_alt::thread_tmp_47_cast_fu_480_p1() {
    tmp_47_cast_fu_480_p1 = esl_zext<64,6>(tmp_41_fu_475_p2.read());
}

void back_substitute_alt::thread_tmp_49_cast_fu_440_p1() {
    tmp_49_cast_fu_440_p1 = esl_zext<6,5>(tmp_42_fu_432_p3.read());
}

void back_substitute_alt::thread_tmp_50_cast_fu_519_p1() {
    tmp_50_cast_fu_519_p1 = esl_zext<64,6>(tmp_43_reg_810.read());
}

void back_substitute_alt::thread_tmp_51_cast_fu_454_p1() {
    tmp_51_cast_fu_454_p1 = esl_zext<64,6>(tmp_44_fu_449_p2.read());
}

void back_substitute_alt::thread_tmp_53_cast_fu_414_p1() {
    tmp_53_cast_fu_414_p1 = esl_zext<6,5>(tmp_45_fu_406_p3.read());
}

void back_substitute_alt::thread_tmp_54_cast_fu_423_p1() {
    tmp_54_cast_fu_423_p1 = esl_zext<64,6>(tmp_46_fu_418_p2.read());
}

void back_substitute_alt::thread_tmp_cast_fu_241_p1() {
    tmp_cast_fu_241_p1 = esl_zext<6,3>(i_reg_161.read());
}

void back_substitute_alt::thread_tmp_fu_268_p1() {
    tmp_fu_268_p1 = i_reg_161.read().range(2-1, 0);
}

void back_substitute_alt::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond3_fu_229_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) && !(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(exitcond3_fu_229_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(exitcond2_fu_292_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(exitcond1_fu_350_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else if ((esl_seteq<1,1,1>(tmp_22_fu_362_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(exitcond1_fu_350_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 32 : 
            if (!(esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read()) && esl_seteq<1,1,1>(exitcond_fu_388_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_enable_reg_pp1_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp1_stage0_subdone.read()) && esl_seteq<1,1,1>(exitcond_fu_388_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

}

