// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCHOLESKY_INVERSE_TOP_H
#define XCHOLESKY_INVERSE_TOP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcholesky_inverse_top_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XCholesky_inverse_top_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XCholesky_inverse_top;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XCholesky_inverse_top_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XCholesky_inverse_top_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XCholesky_inverse_top_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XCholesky_inverse_top_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XCholesky_inverse_top_Initialize(XCholesky_inverse_top *InstancePtr, u16 DeviceId);
XCholesky_inverse_top_Config* XCholesky_inverse_top_LookupConfig(u16 DeviceId);
int XCholesky_inverse_top_CfgInitialize(XCholesky_inverse_top *InstancePtr, XCholesky_inverse_top_Config *ConfigPtr);
#else
int XCholesky_inverse_top_Initialize(XCholesky_inverse_top *InstancePtr, const char* InstanceName);
int XCholesky_inverse_top_Release(XCholesky_inverse_top *InstancePtr);
#endif

void XCholesky_inverse_top_Start(XCholesky_inverse_top *InstancePtr);
u32 XCholesky_inverse_top_IsDone(XCholesky_inverse_top *InstancePtr);
u32 XCholesky_inverse_top_IsIdle(XCholesky_inverse_top *InstancePtr);
u32 XCholesky_inverse_top_IsReady(XCholesky_inverse_top *InstancePtr);
void XCholesky_inverse_top_EnableAutoRestart(XCholesky_inverse_top *InstancePtr);
void XCholesky_inverse_top_DisableAutoRestart(XCholesky_inverse_top *InstancePtr);
u32 XCholesky_inverse_top_Get_return(XCholesky_inverse_top *InstancePtr);


void XCholesky_inverse_top_InterruptGlobalEnable(XCholesky_inverse_top *InstancePtr);
void XCholesky_inverse_top_InterruptGlobalDisable(XCholesky_inverse_top *InstancePtr);
void XCholesky_inverse_top_InterruptEnable(XCholesky_inverse_top *InstancePtr, u32 Mask);
void XCholesky_inverse_top_InterruptDisable(XCholesky_inverse_top *InstancePtr, u32 Mask);
void XCholesky_inverse_top_InterruptClear(XCholesky_inverse_top *InstancePtr, u32 Mask);
u32 XCholesky_inverse_top_InterruptGetEnabled(XCholesky_inverse_top *InstancePtr);
u32 XCholesky_inverse_top_InterruptGetStatus(XCholesky_inverse_top *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
